# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-21 01:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Variables',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_type', models.IntegerField(default=0)),
                ('personal_income', models.FloatField(default=0, max_length=100000000)),
                ('family_income', models.FloatField(default=0, max_length=100000000)),
                ('other_income', models.FloatField(default=0, max_length=100000000)),
                ('house_rent', models.FloatField(default=0, max_length=100000000)),
                ('house_utility', models.FloatField(default=0, max_length=100000000)),
                ('house_misc', models.FloatField(default=0, max_length=100000000)),
                ('car_rent', models.FloatField(default=0, max_length=100000000)),
                ('car_miles', models.FloatField(default=0, max_length=100000000)),
                ('car_insurance', models.FloatField(default=0, max_length=100000000)),
                ('phone_rent', models.FloatField(default=0, max_length=100000000)),
                ('phone_usage', models.FloatField(default=0, max_length=100000000)),
                ('phone_insurance', models.FloatField(default=0, max_length=100000000)),
                ('cable_rent', models.FloatField(default=0, max_length=100000000)),
                ('cable_speed', models.FloatField(default=0, max_length=100000000)),
                ('cable_space', models.FloatField(default=0, max_length=100000000)),
                ('phone_subscriptions', models.FloatField(default=0, max_length=100000000)),
                ('computer_subscriptions', models.FloatField(default=0, max_length=100000000)),
                ('other_subscriptions', models.FloatField(default=0, max_length=100000000)),
                ('medical_loan', models.FloatField(default=0, max_length=100000000)),
                ('car_loan', models.FloatField(default=0, max_length=100000000)),
                ('colledge_loan', models.FloatField(default=0, max_length=100000000)),
                ('house_loan', models.FloatField(default=0, max_length=100000000)),
                ('credit_card_loan', models.FloatField(default=0, max_length=100000000)),
                ('misc_loan', models.FloatField(default=0, max_length=100000000)),
                ('family_expenses', models.FloatField(default=0, max_length=100000000)),
                ('medical_expenses', models.FloatField(default=0, max_length=100000000)),
                ('dental_expenses', models.FloatField(default=0, max_length=100000000)),
                ('college_expenses', models.FloatField(default=0, max_length=100000000)),
                ('grocery_expenses', models.FloatField(default=0, max_length=100000000)),
                ('cloth_expesnses', models.FloatField(default=0, max_length=100000000)),
                ('life_insurance_expenses', models.FloatField(default=0, max_length=100000000)),
                ('misc_expenses', models.FloatField(default=0, max_length=100000000)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
