# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-02 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variables',
            name='goal_income',
            field=models.FloatField(default=0, max_length=100000000),
        ),
        migrations.AddField(
            model_name='variables',
            name='years_to_achieve',
            field=models.FloatField(default=0, max_length=100000000),
        ),
    ]
