# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-02 09:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0002_auto_20161202_0855'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variables',
            old_name='colledge_loan',
            new_name='college_loan',
        ),
    ]
