# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-12 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0004_variables_calculate_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variables',
            old_name='calculate_result',
            new_name='monthly_extra_income',
        ),
        migrations.AddField(
            model_name='variables',
            name='monthly_income',
            field=models.FloatField(default=0, max_length=100000000),
        ),
    ]
