# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-15 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0006_auto_20161212_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariableType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_type', models.IntegerField(default=0)),
            ],
        ),
    ]
