# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-06 00:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0007_variabletype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VariableType',
        ),
        migrations.AddField(
            model_name='variables',
            name='monthly_savings',
            field=models.FloatField(default=0, max_length=100000000),
        ),
    ]
