# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-15 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0009_auto_20170114_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variables',
            name='financial_knowledge',
            field=models.CharField(default='', max_length=100),
        ),
    ]
