# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-15 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0010_auto_20170115_0115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variables',
            name='age_date',
        ),
        migrations.RemoveField(
            model_name='variables',
            name='age_month',
        ),
        migrations.RemoveField(
            model_name='variables',
            name='age_year',
        ),
        migrations.AddField(
            model_name='variables',
            name='age',
            field=models.CharField(default='', max_length=100),
        ),
    ]
