# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-15 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0011_auto_20170115_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variables',
            name='client_type',
            field=models.IntegerField(default=4),
        ),
    ]
