# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-15 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0012_auto_20170115_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='variables',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='variables',
            name='client_type',
            field=models.IntegerField(default=0),
        ),
    ]
