# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-15 07:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0013_auto_20170115_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='variables',
            name='key',
            field=models.CharField(default='', max_length=100),
        ),
    ]
