# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-04 01:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0014_variables_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Webinars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('webinar_name', models.CharField(default='', max_length=100)),
                ('webinar_url', models.CharField(default='', max_length=100000000)),
                ('webinar_date', models.CharField(default='', max_length=10)),
            ],
        ),
    ]
