# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-04 01:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0015_webinars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webinars',
            name='webinar_date',
        ),
        migrations.AddField(
            model_name='webinars',
            name='webinar_time',
            field=models.CharField(default='', max_length=20),
        ),
    ]
