# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-04 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0016_auto_20170304_0135'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinars',
            name='webinar_speaker',
            field=models.CharField(default='', max_length=100000000),
        ),
    ]
