# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-07 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0017_webinars_webinar_speaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinars',
            name='webinar_date_of_month',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='webinars',
            name='webinar_day_of_week',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AddField(
            model_name='webinars',
            name='webinar_month',
            field=models.CharField(default='', max_length=2),
        ),
        migrations.AddField(
            model_name='webinars',
            name='webinar_year',
            field=models.CharField(default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='webinars',
            name='webinar_time',
            field=models.CharField(default='', max_length=10),
        ),
    ]
