# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-07 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0018_auto_20170307_0636'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinars',
            name='webinar_month_name',
            field=models.CharField(default='', max_length=3),
        ),
    ]
