# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-07 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0019_webinars_webinar_month_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webinars',
            name='webinar_day_of_week',
            field=models.CharField(default='', max_length=9),
        ),
    ]
