# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-07 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0020_auto_20170307_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='webinars',
            name='webinar_description',
            field=models.TextField(default='', max_length=1000),
        ),
    ]
