# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-10 06:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0021_webinars_webinar_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variables',
            old_name='boolean_colledge_loan',
            new_name='boolean_college_loan',
        ),
    ]
