# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-10 07:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0022_auto_20170310_0606'),
    ]

    operations = [
        migrations.AddField(
            model_name='variables',
            name='booelan_other_purchase_plan',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='variables',
            name='boolean_car_purchase_plan',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='variables',
            name='boolean_children_plan',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='variables',
            name='boolean_college_loan_plan',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='variables',
            name='boolean_home_finance_plan',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='variables',
            name='boolean_marriage_plan',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='variables',
            name='boolean_start_business_plan',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='variables',
            name='cable_insurance_provider',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='variables',
            name='cable_insurance_satisfaction',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='variables',
            name='car_insurance_provider',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='variables',
            name='car_insurance_satisfaction',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='variables',
            name='dental_insurance_provider',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='variables',
            name='dental_insurance_satisfaction',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='variables',
            name='financial_change_speed',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='variables',
            name='health_insurance_provider',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='variables',
            name='health_insurance_satisfaction',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='variables',
            name='house_insurance_provider',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='variables',
            name='house_insurance_satisfaction',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='variables',
            name='investment_interested',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='variables',
            name='life_insurance_provider',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='variables',
            name='life_insurance_satisfaction',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='variables',
            name='percentage_of_income_to_save',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='variables',
            name='phone_insurance_provider',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='variables',
            name='phone_insurance_satisfaction',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='variables',
            name='spending_consideration',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='variables',
            name='vacation_plan',
            field=models.CharField(default='', max_length=100),
        ),
    ]
