# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-14 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0023_auto_20170310_0720'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_value', models.FloatField(default=0, max_length=100000000)),
                ('gas_value', models.FloatField(default=0, max_length=100000000)),
                ('credit_card_value', models.FloatField(default=0, max_length=100000000)),
                ('mortgage_value', models.FloatField(default=0, max_length=100000000)),
                ('credit_score_value', models.FloatField(default=0, max_length=100000000)),
                ('cell_phone_value', models.FloatField(default=0, max_length=100000000)),
                ('income_rate', models.FloatField(default=0, max_length=100000000)),
                ('gas_rate', models.FloatField(default=0, max_length=100000000)),
                ('credit_card_rate', models.FloatField(default=0, max_length=100000000)),
                ('mortgage_rate', models.FloatField(default=0, max_length=100000000)),
                ('credit_score_rate', models.FloatField(default=0, max_length=100000000)),
                ('cell_phone_rate', models.FloatField(default=0, max_length=100000000)),
                ('income_description', models.TextField(default='', max_length=1000)),
                ('gas_description', models.TextField(default='', max_length=1000)),
                ('credit_card_description', models.TextField(default='', max_length=1000)),
                ('mortgage_description', models.TextField(default='', max_length=1000)),
                ('credit_score_description', models.TextField(default='', max_length=1000)),
                ('cell_phone_description', models.TextField(default='', max_length=1000)),
                ('income_logo', models.CharField(default='', max_length=100000000)),
                ('gas_logo', models.CharField(default='', max_length=100000000)),
                ('credit_card_logo', models.CharField(default='', max_length=100000000)),
                ('mortgage_logo', models.CharField(default='', max_length=100000000)),
                ('credit_score_logo', models.CharField(default='', max_length=100000000)),
                ('cell_phone_logo', models.CharField(default='', max_length=100000000)),
            ],
        ),
    ]
