# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-16 23:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0026_variables_financial_knowledge'),
    ]

    operations = [
        migrations.AddField(
            model_name='variables',
            name='boolean_lol',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='variables',
            name='boolean_netflix',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='variables',
            name='boolean_playstation_live',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='variables',
            name='boolean_wow',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='variables',
            name='boolean_xbox_live',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='variables',
            name='boolean_youtube_red',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='variables',
            name='gym_provider',
            field=models.CharField(default='', max_length=100),
        ),
    ]
