# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-17 00:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0027_auto_20170316_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='variables',
            name='dental_insurance_satisfaction',
            field=models.CharField(default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='variables',
            name='boolean_lol',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='variables',
            name='boolean_netflix',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='variables',
            name='boolean_playstation_live',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='variables',
            name='boolean_wow',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='variables',
            name='boolean_xbox_live',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='variables',
            name='boolean_youtube_red',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='variables',
            name='cable_provider',
            field=models.CharField(default='Other', max_length=100),
        ),
        migrations.AlterField(
            model_name='variables',
            name='cable_satisfaction',
            field=models.CharField(default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='variables',
            name='car_insruance_provider',
            field=models.CharField(default='Other', max_length=100),
        ),
        migrations.AlterField(
            model_name='variables',
            name='car_insurance_satisfaction',
            field=models.CharField(default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='variables',
            name='car_loan_manageable',
            field=models.CharField(default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='variables',
            name='car_loan_provider',
            field=models.CharField(default='Other', max_length=100),
        ),
        migrations.AlterField(
            model_name='variables',
            name='car_satisfaction',
            field=models.CharField(default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='variables',
            name='change_expense_habit',
            field=models.CharField(default='Very Little', max_length=100),
        ),
        migrations.AlterField(
            model_name='variables',
            name='dental_insurance_provider',
            field=models.CharField(default='Other', max_length=100),
        ),
        migrations.AlterField(
            model_name='variables',
            name='gym_provider',
            field=models.CharField(default='Other', max_length=100),
        ),
        migrations.AlterField(
            model_name='variables',
            name='have_car_loan',
            field=models.CharField(default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='variables',
            name='have_job',
            field=models.CharField(default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='variables',
            name='health_insruance_satisfaction',
            field=models.CharField(default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='variables',
            name='health_insurance_provider',
            field=models.CharField(default='Other', max_length=100),
        ),
        migrations.AlterField(
            model_name='variables',
            name='mortgage_manageable',
            field=models.CharField(default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='variables',
            name='mortgage_provider',
            field=models.CharField(default='Other', max_length=100),
        ),
        migrations.AlterField(
            model_name='variables',
            name='mortgage_satisfaction',
            field=models.CharField(default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='variables',
            name='phone_length',
            field=models.CharField(default='1-2 years', max_length=100),
        ),
        migrations.AlterField(
            model_name='variables',
            name='phone_provider',
            field=models.CharField(default='Other', max_length=100),
        ),
        migrations.AlterField(
            model_name='variables',
            name='phone_satisfaction',
            field=models.CharField(default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='variables',
            name='student_loan_manageable',
            field=models.CharField(default='No', max_length=100),
        ),
        migrations.AlterField(
            model_name='variables',
            name='work_length',
            field=models.CharField(default='1-2 years', max_length=100),
        ),
    ]
