# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-17 00:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0029_auto_20170317_0012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variables',
            old_name='car_insruance_provider',
            new_name='car_insurance_provider',
        ),
    ]
