# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-18 22:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0030_auto_20170317_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='cell_phone_url',
            field=models.CharField(default='', max_length=100000000),
        ),
        migrations.AddField(
            model_name='news',
            name='credit_card_url',
            field=models.CharField(default='', max_length=100000000),
        ),
        migrations.AddField(
            model_name='news',
            name='credit_score_url',
            field=models.CharField(default='', max_length=100000000),
        ),
        migrations.AddField(
            model_name='news',
            name='gas_url',
            field=models.CharField(default='', max_length=100000000),
        ),
        migrations.AddField(
            model_name='news',
            name='income_url',
            field=models.CharField(default='', max_length=100000000),
        ),
        migrations.AddField(
            model_name='news',
            name='mortgage_url',
            field=models.CharField(default='', max_length=100000000),
        ),
    ]
