# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-23 01:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Calculator', '0031_auto_20170318_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_evaluated', models.BooleanField(default=False)),
                ('client_level', models.IntegerField(default=1)),
                ('client_action_level', models.IntegerField(default=1)),
                ('raise_cloth', models.BooleanField(default=False)),
                ('cloth_urgent', models.BooleanField(default=False)),
                ('cloth_evaluation', models.TextField(default='', max_length=100)),
                ('raise_food', models.BooleanField(default=False)),
                ('food_urgent', models.BooleanField(default=False)),
                ('food_evaluation', models.TextField(default='', max_length=100)),
                ('raise_education', models.BooleanField(default=False)),
                ('education_urgent', models.BooleanField(default=False)),
                ('education_evaluation', models.TextField(default='', max_length=100)),
                ('raise_gym', models.BooleanField(default=False)),
                ('gym_urgent', models.BooleanField(default=False)),
                ('gym_evaluation', models.TextField(default='', max_length=100)),
                ('raise_savings', models.BooleanField(default=False)),
                ('savings_urgent', models.BooleanField(default=False)),
                ('savings_evaluation', models.TextField(default='', max_length=100)),
                ('raise_house', models.BooleanField(default=False)),
                ('house_urgent', models.BooleanField(default=False)),
                ('house_evaluation', models.TextField(default='', max_length=100)),
                ('raise_car', models.BooleanField(default=False)),
                ('car_urgent', models.BooleanField(default=False)),
                ('car_evaluation', models.TextField(default='', max_length=100)),
                ('raise_gas', models.BooleanField(default=False)),
                ('gas_urgent', models.BooleanField(default=False)),
                ('gas_evaluation', models.TextField(default='', max_length=100)),
                ('raise_phone', models.BooleanField(default=False)),
                ('phone_urgent', models.BooleanField(default=False)),
                ('phone_evaluation', models.TextField(default='', max_length=100)),
                ('raise_cable', models.BooleanField(default=False)),
                ('cable_urgent', models.BooleanField(default=False)),
                ('cable_evaluation', models.TextField(default='', max_length=100)),
                ('raise_health_insurance', models.BooleanField(default=False)),
                ('health_insurance_urgent', models.BooleanField(default=False)),
                ('health_insurance_evaluation', models.TextField(default='', max_length=100)),
                ('raise_dental_insurance', models.BooleanField(default=False)),
                ('dental_insurance_urgent', models.BooleanField(default=False)),
                ('dental_insurance_evaluation', models.TextField(default='', max_length=100)),
                ('raise_credit_card', models.BooleanField(default=False)),
                ('credit_card_urgent', models.BooleanField(default=False)),
                ('credit_card_evaluation', models.TextField(default='', max_length=100)),
                ('raise_debt', models.BooleanField(default=False)),
                ('debt_evaluation', models.TextField(default='', max_length=100)),
                ('raise_income', models.BooleanField(default=False)),
                ('income_evaluation', models.TextField(default='', max_length=100)),
                ('raise_expenses', models.BooleanField(default=False)),
                ('expenses_evaluation', models.TextField(default='', max_length=100)),
                ('monthly_objectives', models.FloatField(default=0, max_length=100000000)),
                ('yearly_objectives', models.FloatField(default=0, max_length=100000000)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
