# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-23 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0032_evaluations'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluations',
            name='car_insurance_evaluation',
            field=models.TextField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='evaluations',
            name='car_insurance_urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evaluations',
            name='raise_car_insurance',
            field=models.BooleanField(default=False),
        ),
    ]
