# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-23 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Calculator', '0033_auto_20170323_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluations',
            name='debt_urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evaluations',
            name='expenses_urgent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='evaluations',
            name='income_urgent',
            field=models.BooleanField(default=False),
        ),
    ]
